version: '3'

services:
  Region-db:
    image: postgres
    environment:
      POSTGRES_USER: os
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: region
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: